### ISSUE TITLE
Error configuring Snapshot master Moodle

### ISSUE THREAD

**Issue by isabelruiz** [vfremaux/moodle-block_vmoodle#6]
Hi,
First of all, sorry for my bad english.

I have installed Moodle 2.9.1 on Ubuntu 14.04 and I have conected to a Postgres 9.3.6 database.
My moodle works fine.

Now I have installed VMoodle I have followed installations step: https://docs.moodle.org/23/en/VMoodle_Block

I have modified this two, because of VMoodle admin returns errors and some users solved these:
* /moodle/lib/classes/component.php add 'block' on line 48
* /moodle/blocks/vmoodle/controller.management.php replace Mnet_Peer.class.php' to Mnet_Peer.php

After this, I tried to configure VMoodle. First I configure VMoodle on VMoodle setting, later I have open Sites Administration->Server->Moodle virtual instance administration

Moodle notice me "No virtual moodle defined" so I press "snapshot master Moodle".
Moodle shows me: STEP 1 on 3 : Snapshot preparation done. Next step will copy the database. This operation can be long depending on the database size.
I press "Continue" buttom and them Moodle shows me:
"Coding error detected, it must be fixed by a programmer: Invalid state passed to moodle_page::set_state. We are in state 2 and state 1 was requested."
Debug info: 
Error code: codingerror
Stack trace:
line 883 of /lib/pagelib.php: coding_exception thrown
line 940 of /lib/outputrenderers.php: call to moodle_page->set_state()
line 137 of /blocks/vmoodle/view.php: call to core_renderer->header()

Can any one tell me what can be wrong?

I have tried differents VMoodle settings and it always returns me same error.

Thanks in advance

**Comment by pavelxkrejci** [comment]
Hello Isabel,
there are a few errors in this version of VMoodle plugin. I don't know if it can even run with Moodle 2.9.x. 
I would recommend to try 2.7.x.

However, to work around this specific error edit /blocks/vmoodle/view.php
comment out lines 132 and 134, but not line 133:
//        echo $OUTPUT->header();
          echo $OUTPUT->notification($e->getMessage());
//        echo $OUTPUT->footer();

**Comment by isabelruiz** [comment]
Hello,

I have followed your advice and I have discard Moodle 2.9 (maybe later I will install it again).

So I have installed Moodle 2.7 and comment out lines 132 and 134.

Now it works.

Thanks.
